_schema: _schema
source: /src/
paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: content/pages
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_url: true
    description: ''
    _editables:
      content:
        allow_custom_markup: false
        remove_custom_markup: false
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code: true
        copyformatting: true
        embed: true
        expandable: true
        format:
        height:
        horizontalrule: true
        image: true
        image_size_attributes: true
        indent: true
        italic: true
        justify:
        left:
        link: true
        mime_type:
        numberedlist: true
        outdent: true
        paths:
        redo: true
        removeformat: true
        resize_style:
        right:
        snippet: true
        strike: true
        styles:
        subscript: true
        superscript: true
        table: true
        underline: true
        undo: true
        width:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  config:
    path: config
    name: Config
    icon: coffee
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  contact:
    path: content/contact
    name: Contact
    icon: contacts
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  faq:
    path: content/faq
    name: Faq
    icon: fax
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  homepage:
    path: content/homepage
    name: Homepage
    icon: compare
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pricing:
    path: content/pricing
    name: Pricing
    icon: dining
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/Edmonton
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
